name: noticias
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  animate_do: ^4.2.0
  connectivity_plus: ^7.0.0
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_riverpod: ^2.6.1
  go_router: ^17.0.1
  google_fonts: ^6.3.3
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  lucide_icons: ^0.257.0
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/news_app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/news_app_icon.png
